
import { ComponentMeta } from './types';

export const COMPONENTS: ComponentMeta[] = [
  {
    id: 'holographic-impulse',
    name: 'Glowing 3D Button',
    category: 'input',
    description: 'A button that projects a volumetric shadow and interactive light-field into the virtual Z-space of the container.',
    interactionModel: 'Proximity-driven shadow translation and color-bleed. Click triggers a multi-layered photonic ripple.',
    motionLogic: 'Z-axis displacement and dynamic box-shadow scaling mapped to cursor distance.',
    useCases: ['Primary actions', 'Futuristic interfaces', 'High-priority triggers'],
    difficulty: 'medium',
    keywords: ['button', 'click', 'trigger', 'action', 'press', 'interactive']
  },
  {
    id: 'pressure-execution',
    name: 'Long-Press Confirm Button',
    category: 'input',
    description: 'A button that treats time-held as physical pressure. Requires a sustained temporal hold to overcome magnetic stasis and execute.',
    interactionModel: 'Hold to build potential energy. Visualizes structural compression and chromatic heat-buildup.',
    motionLogic: 'Continuous linear interpolation of scale and blur while active, settling with high-damping spring physics on release.',
    useCases: ['Destructive actions', 'Confirmations', 'Secure gates'],
    difficulty: 'high',
    keywords: ['button', 'hold', 'press', 'longpress', 'confirm', 'execution', 'security']
  },
  {
    id: 'vector-skew-trigger',
    name: 'Cursor-Tracking Skew Button',
    category: 'input',
    description: 'A button that skews its geometry and hit-box based on the cursors angle of approach, meeting the user intent vector halfway.',
    interactionModel: 'Calculates the approach angle (atan2) to apply a technical geometric skew and lean.',
    motionLogic: 'Rotation and skew transform mapping based on polar coordinate distance.',
    useCases: ['Interactive dashboards', 'Gaming UI', 'Experimental navigation'],
    difficulty: 'medium',
    keywords: ['button', 'skew', 'vector', 'angle', 'intent', 'direction']
  },
  {
    id: 'vortex-accretion-loader',
    name: 'Spiraling Progress Circle',
    category: 'feedback',
    description: 'A circular progress entity where data "mass" spirals into a central singularity, increasing angular velocity as it nears completion.',
    interactionModel: 'Non-linear orbital acceleration. Outer rings collapse inward as progress increases.',
    motionLogic: 'Polar coordinate interpolation with centrifugal force simulation and radial blur.',
    useCases: ['System initialization', 'Data merging', 'Quantum computations'],
    difficulty: 'high',
    keywords: ['loading', 'spinner', 'progress', 'waiting', 'circle', 'vortex', 'accretion']
  },
  {
    id: 'bismuth-growth-loader',
    name: 'Growing 3D Crystal Stack',
    category: 'feedback',
    description: 'Progress visualized as iridescent geometric strata stacking vertically, mimicking the recursive growth patterns of Bismuth crystals.',
    interactionModel: 'Step-based vertical growth with chromatic shift on each layer addition.',
    motionLogic: 'Isometric transform stacking with staggered spring physics and hue-rotation cycles.',
    useCases: ['File assembly', 'Memory allocation', 'Organic processing'],
    difficulty: 'medium',
    keywords: ['loading', 'progress', 'stack', '3d', 'geometric', 'growth', 'crystals']
  },
  {
    id: 'plasma-conduit-loader',
    name: 'Liquid Loading Bar',
    category: 'feedback',
    description: 'A horizontal loading chamber where blobs of data-plasma merge and pulse within a high-viscosity electromagnetic field.',
    interactionModel: 'Dynamic fluid merging. "Blobs" of progress coalesce as completion increases.',
    motionLogic: 'SVG gooey filters combined with turbulent displacement and sine-wave oscillation.',
    useCases: ['High-bandwidth streaming', 'Energy monitoring', 'Experimental data feeds'],
    difficulty: 'high',
    keywords: ['loading', 'progress', 'fluid', 'gooey', 'plasma', 'conduit', 'liquid']
  },
  {
    id: 'quantum-swarm-cursor',
    name: 'Particle Swarm Cursor',
    category: 'motion',
    description: 'A cloud of high-entropy particles that follow the cursor with stochastic inertia, condensing into a core during stasis.',
    interactionModel: 'Multi-agent spring physics. Velocity dictates particle dispersion and trail length.',
    motionLogic: 'Independent spring-damped agents with randomized temporal offsets.',
    useCases: ['Immersive storytelling', 'Experimental portfolios', 'High-energy dashboards'],
    difficulty: 'high',
    keywords: ['mouse', 'pointer', 'cursor', 'particles', 'swarm', 'follow', 'velocity']
  },
  {
    id: 'tactical-scan-cursor',
    name: 'Tactical HUD Crosshair',
    category: 'motion',
    description: 'A military-grade tactical crosshair that projects coordinate axes and telemetry metadata across the container field.',
    interactionModel: 'Axis-linked projection lines with real-time coordinate and velocity readout.',
    motionLogic: 'Screen-space coordinate mapping with linear interpolation and rotational radar sweeps.',
    useCases: ['Technical tools', 'Gaming UI', 'Precision dashboards'],
    difficulty: 'medium',
    keywords: ['mouse', 'pointer', 'cursor', 'crosshair', 'hud', 'scanning', 'precision']
  },
  {
    id: 'elastic-tendril-cursor',
    name: 'Elastic Jellyfish Trail',
    category: 'motion',
    description: 'Organic SVG tendrils that trail the cursor with variable viscosity, creating a fluid jellyfish-like movement signature.',
    interactionModel: 'Staggered path-following with high-damping spring physics.',
    motionLogic: 'Procedural SVG path interpolation using a temporal coordinate buffer.',
    useCases: ['Atmospheric sites', 'Creative interactive art', 'Nature-inspired UI'],
    difficulty: 'high',
    keywords: ['mouse', 'pointer', 'cursor', 'organic', 'trail', 'viscous', 'fluid']
  },
  {
    id: 'history-strata',
    name: '3D Parallax Timeline',
    category: 'navigation',
    description: 'A narrative-driven timeline where history is stratified in 3D space. Eras emerge from temporal fog and crystallize into sharp focus as the user scrolls through the epoch.',
    interactionModel: 'Vertical scroll drives temporal depth. Focal events scale and sharpen while background eras parallax in Z-space.',
    motionLogic: 'Scroll-linked Z-axis translation combined with focal blur interpolation and elastic spine deformation.',
    useCases: ['Company histories', 'Product roadmaps', 'Evolutionary timelines'],
    difficulty: 'high',
    keywords: ['navigation', 'timeline', 'scroll', 'z-space', 'history', 'parallax']
  },
  {
    id: 'kinetic-timeline',
    name: 'Interactive Film Strip',
    category: 'navigation',
    description: 'A non-linear timeline that treats time as a physical medium. Events are stratified in Z-space and respond to scrubbing velocity with elastic deformation.',
    interactionModel: 'Drag the photonic playhead to scrub. High velocity triggers focal distortion. Event nodes drift in Z-depth based on temporal distance from focus.',
    motionLogic: 'Mass-spring playhead physics (stiffness: 120, damping: 20) with velocity-mapped chromatic aberration and Gaussian blur.',
    useCases: ['Video editing suites', 'Historical data exploration', 'Process scrubbing'],
    difficulty: 'high',
    keywords: ['navigation', 'timeline', 'scroll', 'scrub', 'video', 'editing', 'playback']
  },
  {
    id: 'strata-loader',
    name: 'Layered Loading Stack',
    category: 'feedback',
    description: 'A volumetric progress stack revealing data completion across independent Z-plane strata with staggered temporal offsets.',
    interactionModel: 'Auto-cycling progress. Visualizes the "depth" of data arriving in the system buffer.',
    motionLogic: 'Z-axis displacement combined with staggered ease-out curves.',
    useCases: ['Spatial dashboards', 'Complex file processing', 'Depth-heavy UIs'],
    difficulty: 'medium',
    keywords: ['loading', 'progress', 'depth', '3d', 'strata', 'layers']
  },
  {
    id: 'tectonic-loader',
    name: 'Physics-Based Progress',
    category: 'feedback',
    description: 'A progress indicator that treats data arrival as a physical collision. Progress segments overshoot and settle with high-viscosity spring inertia.',
    interactionModel: 'Auto-cycling progress with manual override. Observes kinetic overshoot on state change.',
    motionLogic: 'Damped spring physics (stiffness: 80, damping: 12) applied to linear width.',
    useCases: ['System loading', 'File transfers', 'Physics-heavy UIs'],
    difficulty: 'low',
    keywords: ['loading', 'progress', 'heavy', 'physics', 'tectonic', 'mass']
  },
  {
    id: 'photonic-loader',
    name: 'Glowing Beam Progress',
    category: 'feedback',
    description: 'A volumetric light-seed that bleeds photonic energy into the background medium as it traverses the progress track.',
    interactionModel: 'Light spill intensity scales with progress velocity.',
    motionLogic: 'Radial gradient masks with variable blur and opacity decay.',
    useCases: ['Atmospheric dashboards', 'Premium wait states', 'Data streaming'],
    difficulty: 'medium',
    keywords: ['loading', 'progress', 'light', 'beam', 'glow', 'photonic']
  },
  {
    id: 'entropy-loader',
    name: 'Fuzzy Noise Reveal',
    category: 'feedback',
    description: 'Information emerging from digital chaos. The loader begins as high-frequency visual noise and crystallizes into a solid block as it nears completion.',
    interactionModel: 'Noise-to-signal ratio is inverse-mapped to progress percentage.',
    motionLogic: 'Procedural noise filters and clip-path randomization.',
    useCases: ['Secure boot', 'AI processing', 'Cryptographic tasks'],
    difficulty: 'high',
    keywords: ['loading', 'progress', 'noise', 'static', 'entropy', 'reveal', 'chaos']
  },
  {
    id: 'velocity-cursor',
    name: 'Stretchy Speed Cursor',
    category: 'motion',
    description: 'An intent-aware cursor entity that physically deforms into a kinetic "pill" shape based on real-time movement velocity.',
    interactionModel: 'Mouse speed determines stretch factor and rotation angle.',
    motionLogic: 'useVelocity mapping to scaleX and rotation transform matrices.',
    useCases: ['Creative portfolios', 'High-speed navigation', 'Immersive storytelling'],
    difficulty: 'medium',
    keywords: ['mouse', 'pointer', 'cursor', 'speed', 'stretch', 'velocity']
  },
  {
    id: 'tether-cursor',
    name: 'Magnetic Tether Cursor',
    category: 'motion',
    description: 'A spatial navigation cursor that projects a dynamic SVG tether line to the nearest interactive anchor point within its influence field.',
    interactionModel: 'Calculates 1/r² proximity to draw elastic connections to system nodes.',
    motionLogic: 'Vector distance calculations mapped to SVG line coordinates.',
    useCases: ['Complex node maps', 'Interactive galleries', 'Guided UX'],
    difficulty: 'high',
    keywords: ['mouse', 'pointer', 'cursor', 'magnetic', 'link', 'tether', 'anchor']
  },
  {
    id: 'field-cursor',
    name: 'Bouncing Grid Background',
    category: 'motion',
    description: 'A cursor that acts as a local gravity well, causing background coordinate nodes to shrink or expand as the user passes over them.',
    interactionModel: 'Proximity-based repulsion field affecting the local grid topology.',
    motionLogic: 'Spring-driven displacement vectors applied to a coordinate grid.',
    useCases: ['Interactive backgrounds', 'Sensory feedback', 'Atmospheric UI'],
    difficulty: 'medium',
    keywords: ['mouse', 'pointer', 'cursor', 'grid', 'repulsion', 'gravity', 'field']
  },
  {
    id: 'tectonic-accordion',
    name: 'Colliding Panels',
    category: 'navigation',
    description: 'A multi-layered information rift where sections physically collide and displace neighbors using rigid-body physics.',
    interactionModel: 'Selecting a rift causes a structural shift, pushing other layers into a compressed stack.',
    motionLogic: 'Spring-driven displacement with elastic collision damping.',
    useCases: ['Complex settings', 'Data-heavy reveals', 'Hierarchical navigation'],
    difficulty: 'high',
    keywords: ['navigation', 'accordion', 'panels', 'collision', 'tectonic', 'stack']
  },
  {
    id: 'trail-cursor',
    name: 'Ghostly Mouse Trail',
    category: 'motion',
    description: 'A custom cursor entity that leaves a temporal "memory" of its path, visualizing the users velocity and intent.',
    interactionModel: 'Cursor-driven trail. High-speed movement creates longer, sharper echoes.',
    motionLogic: 'Temporal buffer sampling with opacity and scale decay curves.',
    useCases: ['Immersive galleries', 'Interactive storytelling', 'Visual feedback'],
    difficulty: 'medium',
    keywords: ['mouse', 'pointer', 'cursor', 'trail', 'memory', 'echo', 'ghost']
  },
  {
    id: 'kinetic-status',
    name: 'Bending Status Icons',
    category: 'feedback',
    description: 'A status indicator where "Check" and "Cross" symbols are procedural wires that bend into state-forms.',
    interactionModel: 'State toggle triggers a geometric re-routing of the symbols structural lines.',
    motionLogic: 'SVG path interpolation with varying stroke-dasharray tension.',
    useCases: ['Form validation', 'System health', 'Task completion'],
    difficulty: 'medium',
    keywords: ['status', 'icon', 'check', 'error', 'morph', 'feedback']
  },
  {
    id: 'velocity-scrollbar',
    name: 'Flexible Thick Scrollbar',
    category: 'navigation',
    description: 'A navigation spine that reacts to scroll speed, expanding into a high-visibility handle during rapid travel.',
    interactionModel: 'Scroll-velocity modulates the thickness and luminance of the scroll indicator.',
    motionLogic: 'Velocity mapping to CSS variables for width and filter intensity.',
    useCases: ['Deep archives', 'Timeline scrubbing', 'Data feeds'],
    difficulty: 'low',
    keywords: ['navigation', 'scrollbar', 'scroll', 'velocity', 'spine']
  },
  {
    id: 'refractive-image',
    name: 'Bubble Zoom Lens',
    category: 'feedback',
    description: 'Media elements that distort like looking through a liquid lens, reacting to the cursors focal pressure.',
    interactionModel: 'Hovering over the media creates a refractive distortion field.',
    motionLogic: 'CSS mask-image + Displacement maps (simulated via SVG filters).',
    useCases: ['Premium portfolios', 'Product showcases', 'Artistic media'],
    difficulty: 'high',
    keywords: ['image', 'zoom', 'refraction', 'liquid', 'lens', 'distortion']
  },
  {
    id: 'neural-badge',
    name: 'Breathing Health Badge',
    category: 'feedback',
    description: 'Status badges that pulse with biological rhythmic patterns to communicate system vitality.',
    interactionModel: 'Ambient animation that reacts to global system entropy.',
    motionLogic: 'Multi-layered sinusoidal scaling and blur oscillation.',
    useCases: ['Live metrics', 'User status', 'System health'],
    difficulty: 'low',
    keywords: ['badge', 'status', 'tag', 'pulse', 'neural', 'vitality']
  },
  {
    id: 'decay-timer',
    name: 'Shattering Digital Clock',
    category: 'feedback',
    description: 'Time visualized as a structural entity that physically disintegrates as entropy increases.',
    interactionModel: 'Countdown timer that triggers geometric collapse.',
    motionLogic: 'Fragmented clip-path animation with particle dispersion.',
    useCases: ['Expiring sessions', 'Time-limited tasks', 'Auction timers'],
    difficulty: 'high',
    keywords: ['timer', 'clock', 'time', 'decay', 'shatter', 'disintegrate']
  },
  {
    id: 'bio-profile',
    name: 'Glow-Map User Card',
    category: 'motion',
    description: 'User identity cards visualized as energy fields that heat up or cool down based on activity telemetry.',
    interactionModel: 'Interaction increases the cards "thermal energy" and glow radius.',
    motionLogic: 'Gaussian blur accumulation and chromatic color shifting.',
    useCases: ['Social dashboards', 'Team activity', 'User presence'],
    difficulty: 'medium',
    keywords: ['profile', 'card', 'identity', 'thermal', 'energy', 'user']
  },
  {
    id: 'action-impulse',
    name: 'Shockwave Ripple Button',
    category: 'input',
    description: 'A trigger that treats a click as a kinetic event, propagating a shockwave through the layout medium.',
    interactionModel: 'Click triggers a radial displacement field. Hover creates a pre-stress vibration.',
    motionLogic: 'Wave propagation using expanding concentric masks and spring-back scale.',
    useCases: ['Impactful actions', 'System resets', 'High-energy CTAs'],
    difficulty: 'medium',
    keywords: ['button', 'click', 'trigger', 'shockwave', 'impulse', 'ripple']
  },
  {
    id: 'sequence-strata',
    name: 'Peeling Folder List',
    category: 'navigation',
    description: 'A vertical sequence where items are stratified in Z-depth, revealed via focal slicing.',
    interactionModel: 'Vertical movement "peels" back the top layer to reveal the underlying sequence item.',
    motionLogic: 'CSS clip-path interpolation combined with logarithmic Z-scaling.',
    useCases: ['Product feeds', 'Storytelling lists', 'Portfolio navigation'],
    difficulty: 'high',
    keywords: ['navigation', 'list', 'sequence', 'strata', 'layers', 'depth']
  },
  {
    id: 'portal-branch',
    name: 'Blooming Circle Menu',
    category: 'navigation',
    description: 'A radial navigation entity that branches from a central intent node.',
    interactionModel: 'Selection expands into a recursive tree of possibilities. Lines represent logical connection.',
    motionLogic: 'L-system branching animation with spring-force layout nodes.',
    useCases: ['Complex menus', 'Feature discovery', 'Logic branching'],
    difficulty: 'high',
    keywords: ['navigation', 'menu', 'radial', 'branch', 'portal', 'tree']
  },
  {
    id: 'friction-toggle',
    name: 'Heavy Pull Switch',
    category: 'input',
    description: 'A state switcher that requires physical momentum to overcome its structural magnetic lock.',
    interactionModel: 'Drag-based interaction with a "snap-zone" that resists transition until high velocity is reached.',
    motionLogic: 'Bimodal spring physics with a non-linear friction curve.',
    useCases: ['Critical switches', 'Security toggles', 'Intentional states'],
    difficulty: 'medium',
    keywords: ['input', 'toggle', 'switch', 'friction', 'momentum', 'security']
  },
  {
    id: 'liquid-tab',
    name: 'Melting Liquid Tabs',
    category: 'navigation',
    description: 'Switching context is a fluid event. The indicator physically "melts" and flows between positions.',
    interactionModel: 'Horizontal selection triggers a gooey-filtered transition between states.',
    motionLogic: 'SVG Gaussian blur + Color matrix contrast filtering (Gooey effect).',
    useCases: ['Dashboard navigation', 'Mode switching', 'Filtering'],
    difficulty: 'medium',
    keywords: ['navigation', 'tabs', 'liquid', 'melting', 'gooey', 'indicator']
  },
  {
    id: 'vortex-dial',
    name: 'Spinning Vortex Dial',
    category: 'input',
    description: 'A circular input where the speed of rotation is as important as the final value.',
    interactionModel: 'Rotation modulates the focal value; high-speed rotation triggers "Centrifugal mode".',
    motionLogic: 'Angular velocity mapping to particle dispersion and blur.',
    useCases: ['Volume control', 'Temporal scrubbing', 'Parameter tuning'],
    difficulty: 'high',
    keywords: ['input', 'dial', 'knob', 'rotate', 'vortex', 'centrifugal']
  },
  {
    id: 'impulse-signal',
    name: 'Glitch Alert Banner',
    category: 'feedback',
    description: 'Notifications are temporary glitches in system stability, demanding attention through structural noise.',
    interactionModel: 'Temporal manifestation. The UI "breaks" briefly to show the message then repairs itself.',
    motionLogic: 'Horizontal slice displacement and chromatic aberration pulses.',
    useCases: ['System alerts', 'Error states', 'High-priority messages'],
    difficulty: 'medium',
    keywords: ['notification', 'alert', 'glitch', 'error', 'signal', 'impulse']
  },
  {
    id: 'volumetric-gauge',
    name: 'Water Level Meter',
    category: 'feedback',
    description: 'Visualizes data volume as a literal physical filling of a translucent geometric vessel.',
    interactionModel: 'Simulates liquid sloshing and surface tension based on data-flow velocity.',
    motionLogic: 'Sine-wave surface perturbation and gravitational settling.',
    useCases: ['Storage meters', 'Progress indicators', 'Load monitoring'],
    difficulty: 'high',
    keywords: ['gauge', 'meter', 'liquid', 'volume', 'tank', 'sloshing']
  },
  {
    id: 'crystallized-text',
    name: 'Jittery Reveal Input',
    category: 'input',
    description: 'Information emerges from digital entropy. Text solidifies as the system gains confidence in the input.',
    interactionModel: 'Typing triggers a crystallization effect where chars jitter into their final sharp state.',
    motionLogic: 'Procedural noise scrambling with linear decoherence curves.',
    useCases: ['Login fields', 'Search bars', 'Title reveals'],
    difficulty: 'medium',
    keywords: ['input', 'text', 'type', 'reveal', 'scramble', 'static']
  },
  {
    id: 'momentum-trigger',
    name: 'Magnetic Snap Button',
    category: 'input',
    description: 'A professional-grade SaaS button with intent-aware magnetic pull and tactile haptic feedback.',
    interactionModel: 'Cursor proximity drives subtle 3D leaning and internal element translation.',
    motionLogic: 'Spring-damped displacement vectors with a 0.98x active compression scale.',
    useCases: ['Primary CTAs', 'Form submission', 'Deliberate actions'],
    difficulty: 'low',
    keywords: ['button', 'click', 'magnetic', 'intent', 'momentum', 'trigger']
  },
  {
    id: 'luminance-mass',
    name: 'Bright Glow Intensity',
    category: 'feedback',
    description: 'Visualizes data magnitude via light intensity and volumetric blur rather than numeric scales.',
    interactionModel: 'Hover to "feel" the data mass through light spill and peripheral glow.',
    motionLogic: 'Inverse-square glow falloff and logarithmic radius scaling.',
    useCases: ['System load monitoring', 'Volume indicators', 'Energy dashboards'],
    difficulty: 'medium',
    keywords: ['glow', 'magnitude', 'light', 'mass', 'photonic', 'volume']
  },
  {
    id: 'kinetic-ticker',
    name: 'Vibrating Live Feed',
    category: 'motion',
    description: 'Communicates data momentum and velocity through rhythmic oscillation and speed of travel.',
    interactionModel: 'The faster the data stream, the more violent the rhythmic "breathing" of the UI.',
    motionLogic: 'Frequency-modulated sine waves applied to scale and opacity.',
    useCases: ['Live stock feeds', 'Real-time traffic', 'Pulse monitors'],
    difficulty: 'medium',
    keywords: ['data', 'ticker', 'vibration', 'feed', 'live', 'momentum']
  },
  {
    id: 'aura-sentiment',
    name: 'Liquid Background Mood',
    category: 'feedback',
    description: 'Translates emotional trends into organic color bleeding and liquid motion signatures.',
    interactionModel: 'Intentional color shifts and "viscosity" changes based on data sentiment scores.',
    motionLogic: 'Perlin noise-based color interpolation and fluid displacement.',
    useCases: ['Social sentiment analysis', 'Brand health', 'Community mood'],
    difficulty: 'high',
    keywords: ['sentiment', 'mood', 'aura', 'color', 'fluid', 'viscosity']
  },
  {
    id: 'viscous-data-feel',
    name: 'Heavy Resistance Drag',
    category: 'input',
    description: 'Data density is communicated through "friction" — interaction becomes physically heavier as complexity increases.',
    interactionModel: 'Cursor resistance and scroll-inertia change based on the active dataset weight.',
    motionLogic: 'Dynamic damping and mass variables applied to spring physics.',
    useCases: ['File size indicators', 'Data heavy list exploration', 'Wait-state feedback'],
    difficulty: 'high',
    keywords: ['input', 'drag', 'viscous', 'friction', 'heavy', 'resistance']
  },
  {
    id: 'magneto-nav',
    name: 'Magnetic Sticky Menu',
    category: 'navigation',
    description: 'A navigation system that exerts a physical pull on the cursor as it passes by linked nodes.',
    interactionModel: 'Cursor-driven magnetic attraction toward nav items.',
    motionLogic: 'Weighted spring physics with distance-based attenuation.',
    useCases: ['High-intent navigation', 'Interactive menus', 'Focused choice selection'],
    difficulty: 'medium',
    keywords: ['navigation', 'menu', 'magnetic', 'nodes', 'magneto']
  },
  {
    id: 'tension-grid',
    name: 'Elastic Canvas Grid',
    category: 'motion',
    description: 'A spatial layout that deforms based on interaction density, like a stretched fabric.',
    interactionModel: 'Cursor proximity causes grid cells to scale and rotate toward the focal point.',
    motionLogic: 'Inverse-square displacement with spring-return tension.',
    useCases: ['Data visualization', 'Atmospheric backgrounds', 'Sensory feedback'],
    difficulty: 'high',
    keywords: ['grid', 'elastic', 'tension', 'canvas', 'deform', 'fabric']
  },
  {
    id: 'chrono-scroll',
    name: 'Warp Speed Scroller',
    category: 'motion',
    description: 'A scroll container that treats the scrollbar as a temporal scrub bar, warping content as speed increases.',
    interactionModel: 'Scroll velocity drives chromatic aberration and scale warping.',
    motionLogic: 'Velocity mapping to multiple CSS filter variables.',
    useCases: ['Long-form storytelling', 'Media feeds', 'Chronological data'],
    difficulty: 'medium',
    keywords: ['scroll', 'time', 'warping', 'chrono', 'aberration', 'velocity']
  },
  {
    id: 'orbit-nexus',
    name: 'Spinning Planet Menu',
    category: 'navigation',
    description: 'A non-linear menu where items orbit the central intent, shifting speed based on focus.',
    interactionModel: 'Polar coordinate navigation with dynamic centrifugal force.',
    motionLogic: 'Sinusoidal path mapping with variable frequency damping.',
    useCases: ['Feature clouds', 'Complexity management', 'Immersive menus'],
    difficulty: 'high',
    keywords: ['navigation', 'menu', 'orbit', 'nexus', 'polar', 'centrifugal']
  },
  {
    id: 'halt-reveal',
    name: 'Hold Still to Reveal',
    category: 'input',
    description: 'Interaction gated by stillness. Information manifests only when user intent stabilizes.',
    interactionModel: 'Hovering without moving for a threshold triggers a content bloom.',
    motionLogic: 'Velocity detection threshold linked to an opacity/scale progress ramp.',
    useCases: ['Deep data exploration', 'Engagement gates', 'Reading modes'],
    difficulty: 'high',
    keywords: ['input', 'reveal', 'stillness', 'halt', 'bloom', 'gate']
  },
  {
    id: 'intent-pulse',
    name: 'Anticipation Glow',
    category: 'feedback',
    description: 'A component that radiates state signals before an action is even confirmed.',
    interactionModel: 'Approach-aware glow and scale shifts.',
    motionLogic: 'Proximity mapping to SVG filters and spring-driven luminance.',
    useCases: ['Critical actions', 'System readiness', 'Success states'],
    difficulty: 'medium',
    keywords: ['glow', 'intent', 'pulse', 'pre-click', 'feedback', 'approach']
  },
  {
    id: 'stochastic-mass',
    name: 'Random Bouncy Body',
    category: 'motion',
    description: 'An entity with randomized physical properties that "learn" user preferences through interaction weight.',
    interactionModel: 'Drag and toss mechanics with random inertia curves.',
    motionLogic: 'Physics-based mass and damping randomization.',
    useCases: ['Playful branding', 'Experimental physics', 'Generative UI'],
    difficulty: 'high',
    keywords: ['motion', 'physics', 'stochastic', 'random', 'mass', 'learning']
  },
  {
    id: 'cognitive-shield',
    name: 'Blurred Background Focus',
    category: 'feedback',
    description: 'UI that protects user focus by dynamically blurring or hiding non-focal information.',
    interactionModel: 'Automatic isolation of focal nodes.',
    motionLogic: 'Z-depth focal blur interpolation.',
    useCases: ['Complex dashboards', 'Developer tools', 'High-load environments'],
    difficulty: 'medium',
    keywords: ['shield', 'focus', 'isolation', 'blur', 'cognitive', 'clarity']
  },
  {
    id: 'glyph-kinetic',
    name: 'Quiet Pulsing Symbols',
    category: 'feedback',
    description: 'Semantic symbols that use rhythmic motion rather than labels to communicate complex states.',
    interactionModel: 'Rhythmic vibration and geometric morphing.',
    motionLogic: 'Frequency-modulated oscillation curves.',
    useCases: ['Textless interfaces', 'Status systems', 'Micro-interactions'],
    difficulty: 'low',
    keywords: ['symbols', 'glyphs', 'kinetic', 'silent', 'motion', 'rhythm']
  },
  {
    id: 'commitment-shard',
    name: 'Glass Shatter Choice',
    category: 'input',
    description: 'A choice mechanism that physically solidifies and "shatters" the alternative upon selection.',
    interactionModel: 'Drag-to-commit with high resistance.',
    motionLogic: 'Physical fragmentation simulation with gravity.',
    useCases: ['High-stakes actions', 'Security gates', 'Final commits'],
    difficulty: 'high',
    keywords: ['input', 'choice', 'commitment', 'shatter', 'fragment', 'selection']
  },
  {
    id: 'confidence-meter',
    name: 'Fluent Typing Effect',
    category: 'feedback',
    description: 'Visualizes input confidence through text clarity and weight.',
    interactionModel: 'Typing speed and consistency drives clarity.',
    motionLogic: 'Blur and weight mapping to user keystroke cadence.',
    useCases: ['Cognitive assessment', 'Interactive logs', 'Flow tracking'],
    difficulty: 'medium',
    keywords: ['meter', 'confidence', 'typing', 'flow', 'clarity', 'weight']
  },
  {
    id: 'resonance-field',
    name: 'Ghostly Mouse Trace',
    category: 'motion',
    description: 'A field where user actions leave persistent "after-glow" resonances that influence future states.',
    interactionModel: 'Cursor actions leave energy traces.',
    motionLogic: 'Temporal alpha decay with spatial persistence.',
    useCases: ['Collaborative heatmaps', 'Interactive art', 'Discovery paths'],
    difficulty: 'high',
    keywords: ['field', 'resonance', 'ghost', 'trace', 'echo', 'memory']
  },
  {
    id: 'evolutionary-shell',
    name: 'Self-Learning Menu',
    category: 'navigation',
    description: 'A UI shell that sheds decorative complexity as user mastery increases over a session.',
    interactionModel: 'Interaction frequency reduces visual labels.',
    motionLogic: 'Semantic state-clipping and icon scaling.',
    useCases: ['Expert tools', 'Onboarding-to-mastery', 'Minimalist systems'],
    difficulty: 'medium',
    keywords: ['navigation', 'adaptive', 'evolutionary', 'mastery', 'minimalism', 'shell']
  },
  {
    id: 'choice-convergence',
    name: 'Target Gravity Select',
    category: 'input',
    description: 'Interactive targets that physically converge or pull toward the user intent vector.',
    interactionModel: 'Proximity-driven gravity wells.',
    motionLogic: 'Attractive spring forces between cursor and target.',
    useCases: ['Form selection', 'Hold-down choice', 'Guided interaction'],
    difficulty: 'medium',
    keywords: ['input', 'choice', 'convergence', 'gravity', 'pull', 'guided']
  },
  {
    id: 'tectonic-data',
    name: 'Shakey Data Feed',
    category: 'feedback',
    description: 'Live data changes cause physical "earthquakes" or shifts in the layout structure.',
    interactionModel: 'UI elements physically settle or collide when data points arrive.',
    motionLogic: 'Rigid-body physics simulation and collision detection.',
    useCases: ['Alert systems', 'Database updates', 'Live sports scores'],
    difficulty: 'high',
    keywords: ['data', 'feed', 'tectonic', 'earthquake', 'collision', 'physics']
  },
  {
    id: 'grid-compression',
    name: 'Tight Packed Grid',
    category: 'navigation',
    description: 'Layout density physically compacts or expands based on data volume, changing the UI "weather".',
    interactionModel: 'The more data exists, the more the layout "compresses" into a dense, high-energy grid.',
    motionLogic: 'Spring-forced repulsion vs attraction grid logic.',
    useCases: ['Calendar density', 'Inventory management', 'Log exploration'],
    difficulty: 'medium',
    keywords: ['navigation', 'grid', 'compression', 'packing', 'density', 'weather']
  },
  {
    id: 'fragile-glass',
    name: 'Exploding Data Panel',
    category: 'feedback',
    description: 'A UI surface that physically shatters into shards when clicked, requiring a temporal recovery phase.',
    interactionModel: 'Click triggers a physics-based fragmentation simulation.',
    motionLogic: 'Polygon clip-path shattering with gravity-based debris fall.',
    useCases: ['Impactful warnings', 'One-way decisions', 'Digital scarcity'],
    difficulty: 'high',
    keywords: ['feedback', 'glass', 'shatter', 'fragment', 'fragile', 'scarcity']
  },
  {
    id: 'cadence-lock',
    name: 'Rhythm Secret Lock',
    category: 'input',
    description: 'An interaction gate that refuses input unless the user matches a specific rhythmic heartbeat.',
    interactionModel: 'Requires rhythmic clicking/tapping within a specific BPM tolerance.',
    motionLogic: 'Sinusoidal visual feedback mapped to precision.',
    useCases: ['Secure auth', 'Mindfulness gates', 'Alternative inputs'],
    difficulty: 'medium',
    keywords: ['input', 'lock', 'rhythm', 'cadence', 'heartbeat', 'security']
  },
  {
    id: 'earned-legibility',
    name: 'Steady Focus Decoder',
    category: 'input',
    description: 'Information is obscured by procedural noise and only decodes when the user maintains perfect focus.',
    interactionModel: 'Cursor stability (zero velocity) triggers the decryption process.',
    motionLogic: 'Noise shader intensity modulated by cursor velocity delta.',
    useCases: ['Deep reading modes', 'Secure data reveal', 'Engagement testing'],
    difficulty: 'high',
    keywords: ['input', 'legibility', 'decrypt', 'focus', 'noise', 'reading']
  },
  {
    id: 'structural-glitch',
    name: 'X-Ray Dev View',
    category: 'feedback',
    description: 'A UI that intentionally "breaks" its own layout rules to reveal the underlying code architecture.',
    interactionModel: 'Hovering over components reveals wireframes, Z-index slices, and raw telemetry.',
    motionLogic: 'State-based interpolation between "Rendered" and "Wireframe" modes.',
    useCases: ['Developer tools', 'Technical branding', 'Creative portfolios'],
    difficulty: 'medium',
    keywords: ['feedback', 'glitch', 'wireframe', 'leak', 'architecture', 'dev']
  },
  {
    id: 'thermal-overload',
    name: 'Overheating Safety Lock',
    category: 'input',
    description: 'A component that "heats up" with rapid interaction, eventually locking out the user to prevent system burnout.',
    interactionModel: 'Cumulative interaction frequency increases a "Thermal" state.',
    motionLogic: 'Chromatic aberration and Gaussian blur intensity mapped to heat levels.',
    useCases: ['Rate-limiting feedback', 'Resource protection', 'Anti-spam UIs'],
    difficulty: 'medium',
    keywords: ['input', 'overload', 'thermal', 'heat', 'limiter', 'rate']
  },
  {
    id: 'rebel-navigation',
    name: 'Swapped Control Menu',
    category: 'navigation',
    description: 'A menu that challenges spatial memory by inverting or randomly remapping its interaction axes.',
    interactionModel: 'Remaps cursor X/Y coordinates to unexpected UI responses.',
    motionLogic: 'Non-linear transform mapping to break standard expectation chains.',
    useCases: ['Skill-based UIs', 'Interactive art', 'Cognitive training'],
    difficulty: 'high',
    keywords: ['navigation', 'rebel', 'axes', 'hijack', 'inverted', 'skill']
  },
  {
    id: 'spatial-strata',
    name: 'Floating Depth Layers',
    category: 'motion',
    description: 'A multi-layered UI where components drift and parallax based on their assigned virtual Z-depth.',
    interactionModel: 'Cursor-driven parallax with independent Z-translation constants.',
    motionLogic: 'Relative transform-3d mapping with spring-based smoothing.',
    useCases: ['Immersive headers', 'Interactive infographics', 'Data storytelling'],
    difficulty: 'medium',
    keywords: ['motion', 'layers', 'parallax', 'spatial', '3d', 'floating']
  },
  {
    id: 'perspective-focal',
    name: 'Warping Perspective Grid',
    category: 'navigation',
    description: 'A UI that warps its vanishing point and layout perspective based on the active focal element.',
    interactionModel: 'Dynamic CSS perspective-origin modulation driven by focus state.',
    motionLogic: 'Interpolated focal point coordinates mapped to container perspective.',
    useCases: ['Spatial menus', 'Focus-driven galleries', '3D dashboards'],
    difficulty: 'high',
    keywords: ['navigation', 'perspective', 'focus', 'vanishing', 'focal', '3d']
  },
  {
    id: 'proximity-field',
    name: 'Smart Focus Blur Grid',
    category: 'feedback',
    description: 'A layout where elements gain detail and sharpness based on their virtual distance from the cursor.',
    interactionModel: 'Calculates 1/r² distance to modulate Gaussian blur and opacity.',
    motionLogic: 'Dynamic filter interpolation based on proximity vectors.',
    useCases: ['Interactive grids', 'Visual search results', 'Focus-aware UIs'],
    difficulty: 'medium',
    keywords: ['feedback', 'proximity', 'field', 'sharpness', 'focus', 'grid']
  },
  {
    id: 'isometric-grid-flux',
    name: 'Tilting 3D Board',
    category: 'navigation',
    description: 'A 2.5D isometric grid that tilts and shears based on viewing angle and interaction.',
    interactionModel: 'Tilting the layout using cursor X/Y coordinates to reveal hidden faces.',
    motionLogic: 'Shear and rotate interpolation for pseudo-3D perspective.',
    useCases: ['Strategy dashboards', 'Resource management UIs', 'Interactive maps'],
    difficulty: 'medium',
    keywords: ['navigation', 'isometric', 'grid', 'tilting', 'flux', '3d']
  },
  {
    id: 'depth-squeeze',
    name: 'Expanding 3D Layers',
    category: 'feedback',
    description: 'A UI that physically flattens into 2D when ignored and expands into a deep Z-stack when engaged.',
    interactionModel: 'Engagement triggers a Z-axis expansion of nested layers.',
    motionLogic: 'Spring physics applied to translateZ and depth separation.',
    useCases: ['Contextual menus', 'Advanced notifications', 'Depth-heavy layouts'],
    difficulty: 'medium',
    keywords: ['feedback', 'depth', 'squeeze', 'stack', 'layers', 'expand']
  },
  {
    id: 'orbital-z-axis',
    name: 'Planetary Circular Nav',
    category: 'navigation',
    description: 'Navigation items that orbit the user in 3D space, moving behind and in front of the primary view.',
    interactionModel: 'Sinusoidal mapping of Z-depth and horizontal position.',
    motionLogic: 'Polar coordinate conversion to 3D Cartesian space.',
    useCases: ['Atmospheric menus', 'Social feeds', 'Ambient navigation'],
    difficulty: 'high',
    keywords: ['navigation', 'orbit', 'planetary', '3d', 'orbital', 'space']
  },
  {
    id: 'state-memory',
    name: 'Smart Preference Tilt',
    category: 'navigation',
    description: 'A layout that physically tilts and biases itself toward the users most recent interactions.',
    interactionModel: 'Stores last-interacted coordinates to influence the default "rest" state of the UI.',
    motionLogic: 'Persistent vector bias applied to spring-based layout nodes.',
    useCases: ['Adaptive menus', 'Personalized tools', 'Smart shortcuts'],
    difficulty: 'medium',
    keywords: ['navigation', 'memory', 'bias', 'recent', 'adaptive', 'state']
  },
  {
    id: 'atrophy-surface',
    name: 'Dusty Idle Effect',
    category: 'feedback',
    description: 'A UI surface that dims and gathers "digital dust" (visual noise) when ignored by the cursor.',
    interactionModel: 'Inactivity timer modulates noise filters and luminance.',
    motionLogic: 'Inverted decay curve mapped to SVG filter intensity.',
    useCases: ['Ambient notifications', 'Energy-saving UIs', 'Dynamic focus systems'],
    difficulty: 'medium',
    keywords: ['feedback', 'atrophy', 'dissolve', 'idle', 'decay', 'dust']
  },
  {
    id: 'circadian-interface',
    name: 'Day & Night Sync',
    category: 'feedback',
    description: 'A UI that shifts its color temperature, shadow direction, and energy based on a simulated time-of-day cycle.',
    interactionModel: 'Visual properties synchronized to a global 24h clock.',
    motionLogic: 'Trigonometric mapping of time to light-source vectors.',
    useCases: ['Health-tech apps', 'Smart home dashboards', 'Atmospheric portfolios'],
    difficulty: 'low',
    keywords: ['feedback', 'circadian', 'day-night', 'sync', 'time', 'lighting']
  },
  {
    id: 'history-echo',
    name: 'Past Path Trails',
    category: 'navigation',
    description: 'A navigation system that leaves "ghostly" trails of its previous states, allowing users to scrub through temporal history.',
    interactionModel: 'Snapshot capture on state change with a persistence scrub interaction.',
    motionLogic: 'Temporal stacking with opacity decay and Z-index layering.',
    useCases: ['Complex workflows', 'Version control visualization', 'Undo/Redo interactions'],
    difficulty: 'high',
    keywords: ['navigation', 'history', 'echo', 'ghost', 'stacking', 'trails']
  },
  {
    id: 'velocity-reader',
    name: 'Blurry Fast Reader',
    category: 'feedback',
    description: 'A text rendering engine that dynamically skews and blurs typography based on scroll velocity.',
    interactionModel: 'Scroll speed drives font-skew and tracking expansion.',
    motionLogic: 'Linear velocity mapping to font-variation axes.',
    useCases: ['Kinetic landing pages', 'Dynamic archives'],
    difficulty: 'medium',
    keywords: ['velocity', 'reader', 'text', 'skew']
  },
  {
    id: 'edge-manifest',
    name: 'Hidden Edge Menu',
    category: 'navigation',
    description: 'Navigation elements that only manifest from the edges of the screen upon high-velocity proximity.',
    interactionModel: 'Edge collision detection with spring expansion.',
    motionLogic: 'Elastic boundaries and clip-path reveals.',
    useCases: ['Minimalist layouts', 'Immersive menus'],
    difficulty: 'medium',
    keywords: ['edge', 'menu', 'reveal']
  },
  {
    id: 'spatial-tunnel',
    name: 'Infinite Depth Zoom',
    category: 'motion',
    description: 'A Z-axis navigation tunnel where layers scale and blur past the user during scrolling.',
    interactionModel: 'Continuous Z-depth interpolation.',
    motionLogic: 'Logarithmic scaling and depth-buffer fog.',
    useCases: ['Infinite scrolling lists', '3D headers'],
    difficulty: 'high',
    keywords: ['tunnel', 'zoom', 'depth']
  },
  {
    id: 'personality-matrix',
    name: 'Bouncy Brand Logo',
    category: 'motion',
    description: 'An entity that shifts between aggressive and soft motion personalities based on interaction speed.',
    interactionModel: 'Velocity-driven trait switching.',
    motionLogic: 'Stiffness/Damping parameter interpolation.',
    useCases: ['Interactive branding', 'Dynamic logos'],
    difficulty: 'medium',
    keywords: ['personality', 'matrix', 'logo']
  }
];
