// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../blocks/hrms-overview';

const meta = {
  title: "Blocks/HRMS/People overview",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'fullscreen', docs: { description: { component: "Headcount, attendance, department split and activity feed." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
