// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../blocks/campaign-performance';

const meta = {
  title: "Blocks/Marketing/Campaign performance",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'fullscreen', docs: { description: { component: "Channel KPIs, weekly leads chart and a campaign budget table." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
