// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../blocks/admin-shell';

const meta = {
  title: "Blocks/Layout/Admin shell",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'fullscreen', docs: { description: { component: "Full app frame: grouped sidebar with nested links, topbar with search, alerts and user menu, and a dashboard page." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
