// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../blocks/leave-request-form';

const meta = {
  title: "Blocks/HRMS/Leave request form",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'fullscreen', docs: { description: { component: "Date range, approver combobox, multi-select notify list, working-day count and field validation." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
