// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../blocks/lead-pipeline';

const meta = {
  title: "Blocks/Marketing/Lead pipeline",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'fullscreen', docs: { description: { component: "Drag-and-drop board with column totals and a keyboard-friendly move button." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
