// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../examples/world-clock';

const meta = {
  title: "Time/World clock",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'centered', docs: { description: { component: "Cities with live local time, a day or night icon and the hour difference from you." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
