// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../examples/stat-card';

const meta = {
  title: "Data/Stat card",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'centered', docs: { description: { component: "KPI tile with value, trend delta and a sparkline slot." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
