// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../examples/shimmer-text';

const meta = {
  title: "Display/Shimmer text",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'centered', docs: { description: { component: "Text with a light sweep passing over it." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
