// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../examples/border-beam';

const meta = {
  title: "Display/Border beam",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'centered', docs: { description: { component: "A light beam that circles the border. For pricing cards and featured content." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
