// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../examples/copy-button';

const meta = {
  title: "Inputs/Copy button",
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: 'centered', docs: { description: { component: "Copies text and morphs to a check." } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const Preview: StoryObj<typeof meta> = {};
