// Writes one story per registry entry so Storybook never drifts from the docs site.
// Run: npm run stories:gen (storybook scripts do it for you).
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

const reg = readFileSync('src/registry/index.ts', 'utf8');
const out = 'src/stories';
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

const file = (kind, slug, title, name, wide, desc) => {
  const layout = wide ? 'fullscreen' : 'centered';
  writeFileSync(
    `${out}/${kind}-${slug}.stories.tsx`,
    `// Generated by scripts/gen-stories.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import Demo from '../${kind}/${slug}';

const meta = {
  title: ${JSON.stringify(title)},
  component: Demo,
  tags: ['autodocs'],
  parameters: { layout: '${layout}', docs: { description: { component: ${JSON.stringify(desc)} } } },
} satisfies Meta<typeof Demo>;
export default meta;

export const ${name}: StoryObj<typeof meta> = {};
`,
  );
};

let n = 0;
for (const [, slug, name, cat, desc] of reg.matchAll(/^\s*m\('([^']+)', '([^']+)', '([^']+)', '((?:[^'\\]|\\.)*)'/gm)) {
  const wide = new RegExp(`m\\('${slug}'[^\\n]*wide: true`).test(reg);
  file('examples', slug, `${cat}/${name}`, 'Preview', wide, desc.replace(/\\'/g, "'"));
  n++;
}
for (const [, slug, name, module, desc] of reg.matchAll(/slug: '([^']+)', name: '([^']+)', module: '([^']+)', description: '((?:[^'\\]|\\.)*)'/g)) {
  file('blocks', slug, `Blocks/${module}/${name}`, 'Preview', true, desc.replace(/\\'/g, "'"));
  n++;
}
console.log(`generated ${n} stories`);
